// AUTO-GENERATED by scripts/embed-drizzle.ts. DO NOT EDIT.
export type EmbeddedMeta = { version: string; dialect: string; entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[] }
export const EMBEDDED_META: EmbeddedMeta = {
  "version": "7",
  "dialect": "sqlite",
  "entries": [
    {
      "idx": 0,
      "version": "6",
      "when": 1758744702973,
      "tag": "0000_round_venom",
      "breakpoints": true
    },
    {
      "idx": 1,
      "version": "6",
      "when": 1758955132419,
      "tag": "0001_empty_roxanne_simpson",
      "breakpoints": true
    },
    {
      "idx": 2,
      "version": "6",
      "when": 1758955722396,
      "tag": "0002_little_invaders",
      "breakpoints": true
    },
    {
      "idx": 3,
      "version": "6",
      "when": 1758958839406,
      "tag": "0003_tearful_chronomancer",
      "breakpoints": true
    },
    {
      "idx": 4,
      "version": "6",
      "when": 1758959203299,
      "tag": "0004_soft_sentry",
      "breakpoints": true
    },
    {
      "idx": 5,
      "version": "7",
      "when": 1759084774548,
      "tag": "0005_retire_auto_cleanup",
      "breakpoints": true
    },
    {
      "idx": 6,
      "version": "7",
      "when": 1763729475445,
      "tag": "0006_card_dependencies",
      "breakpoints": true
    }
  ]
}

export type EmbeddedMigration = { tag: string; sql: string }
export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [
  { tag: "0000_round_venom", sql: `CREATE TABLE \`agent_profiles\`
(
    \`id\`          text PRIMARY KEY                  NOT NULL,
    \`project_id\`  text                              NOT NULL,
    \`agent\`       text                              NOT NULL,
    \`name\`        text                              NOT NULL,
    \`config_json\` text                              NOT NULL,
    \`created_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`project_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`agent_profiles_global\`
(
    \`id\`          text PRIMARY KEY                  NOT NULL,
    \`agent\`       text                              NOT NULL,
    \`name\`        text                              NOT NULL,
    \`config_json\` text                              NOT NULL,
    \`created_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`attempt_logs\`
(
    \`id\`         text PRIMARY KEY                  NOT NULL,
    \`attempt_id\` text                              NOT NULL,
    \`ts\`         integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`level\`      text    DEFAULT 'info'            NOT NULL,
    \`message\`    text                              NOT NULL,
    FOREIGN KEY (\`attempt_id\`) REFERENCES \`attempts\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`attempts\`
(
    \`id\`            text PRIMARY KEY                  NOT NULL,
    \`card_id\`       text                              NOT NULL,
    \`board_id\`      text                              NOT NULL,
    \`agent\`         text                              NOT NULL,
    \`status\`        text                              NOT NULL,
    \`base_branch\`   text    DEFAULT 'main'            NOT NULL,
    \`branch_name\`   text                              NOT NULL,
    \`worktree_path\` text                              NOT NULL,
    \`session_id\`    text,
    \`started_at\`    integer,
    \`ended_at\`      integer,
    \`created_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`card_id\`) REFERENCES \`cards\` (\`id\`) ON UPDATE no action ON DELETE cascade,
    FOREIGN KEY (\`board_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`boards\`
(
    \`id\`              text PRIMARY KEY                  NOT NULL,
    \`name\`            text                              NOT NULL,
    \`repository_path\` text                              NOT NULL,
    \`repository_url\`  text,
    \`repository_slug\` text,
    \`created_at\`      integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`      integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`cards\`
(
    \`id\`          text PRIMARY KEY                  NOT NULL,
    \`title\`       text                              NOT NULL,
    \`description\` text,
    \`position\`    integer                           NOT NULL,
    \`column_id\`   text                              NOT NULL,
    \`board_id\`    text,
    \`ticket_key\`  text,
    \`created_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`column_id\`) REFERENCES \`columns\` (\`id\`) ON UPDATE no action ON DELETE cascade,
    FOREIGN KEY (\`board_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE UNIQUE INDEX \`cards_board_ticket_key_idx\` ON \`cards\` (\`board_id\`, \`ticket_key\`);--> statement-breakpoint
CREATE TABLE \`columns\`
(
    \`id\`         text PRIMARY KEY                  NOT NULL,
    \`title\`      text                              NOT NULL,
    \`position\`   integer                           NOT NULL,
    \`board_id\`   text                              NOT NULL,
    \`created_at\` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\` integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`board_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`conversation_items\`
(
    \`id\`         text PRIMARY KEY                  NOT NULL,
    \`attempt_id\` text                              NOT NULL,
    \`seq\`        integer                           NOT NULL,
    \`ts\`         integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`item_json\`  text                              NOT NULL,
    FOREIGN KEY (\`attempt_id\`) REFERENCES \`attempts\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`github_connections\`
(
    \`id\`            text PRIMARY KEY                  NOT NULL,
    \`username\`      text                              NOT NULL,
    \`primary_email\` text,
    \`access_token\`  text                              NOT NULL,
    \`token_type\`    text                              NOT NULL,
    \`scope\`         text,
    \`created_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE \`github_issues\`
(
    \`id\`             text PRIMARY KEY                  NOT NULL,
    \`board_id\`       text                              NOT NULL,
    \`card_id\`        text                              NOT NULL,
    \`owner\`          text                              NOT NULL,
    \`repo\`           text                              NOT NULL,
    \`issue_id\`       text                              NOT NULL,
    \`issue_number\`   integer                           NOT NULL,
    \`title_snapshot\` text                              NOT NULL,
    \`url\`            text                              NOT NULL,
    \`state\`          text                              NOT NULL,
    \`created_at\`     integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`     integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`board_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade,
    FOREIGN KEY (\`card_id\`) REFERENCES \`cards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE \`project_settings\`
(
    \`project_id\`            text PRIMARY KEY                  NOT NULL,
    \`base_branch\`           text    DEFAULT 'main'            NOT NULL,
    \`preferred_remote\`      text,
    \`setup_script\`          text,
    \`dev_script\`            text,
    \`cleanup_script\`        text,
    \`copy_files\`            text,
    \`default_agent\`         text,
    \`default_profile_id\`    text,
    \`auto_cleanup\`          integer DEFAULT false             NOT NULL,
    \`auto_commit_on_finish\` integer DEFAULT false             NOT NULL,
    \`ticket_prefix\`         text    DEFAULT 'PRJ'             NOT NULL,
    \`next_ticket_number\`    integer DEFAULT 1                 NOT NULL,
    \`created_at\`            integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`            integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (\`project_id\`) REFERENCES \`boards\` (\`id\`) ON UPDATE no action ON DELETE cascade
);
` },
  { tag: "0001_empty_roxanne_simpson", sql: `CREATE TABLE \`app_settings\`
(
    \`id\`                   text PRIMARY KEY DEFAULT 'singleton'                   NOT NULL,
    \`theme\`                text             DEFAULT 'system'                      NOT NULL,
    \`language\`             text             DEFAULT 'browser'                     NOT NULL,
    \`telemetry_enabled\`    integer          DEFAULT false                         NOT NULL,
    \`notif_toast_sounds\`   integer          DEFAULT false                         NOT NULL,
    \`notif_desktop\`        integer          DEFAULT false                         NOT NULL,
    \`editor_type\`          text             DEFAULT 'VS_CODE'                     NOT NULL,
    \`editor_command\`       text,
    \`git_user_name\`        text,
    \`git_user_email\`       text,
    \`git_signoff\`          integer          DEFAULT false                         NOT NULL,
    \`git_gpg_sign\`         integer          DEFAULT false                         NOT NULL,
    \`worktrees_root\`       text             DEFAULT '~/.kanbanAI/worktrees'       NOT NULL,
    \`branch_template\`      text             DEFAULT '{prefix}/{ticketKey}-{slug}' NOT NULL,
    \`gh_default_pr_base\`   text,
    \`gh_pr_title_template\` text,
    \`gh_pr_body_template\`  text,
    \`gh_default_reviewers\` text,
    \`gh_default_assignees\` text,
    \`gh_autolink_tickets\`  integer          DEFAULT true                          NOT NULL,
    \`created_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL,
    \`updated_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL
);
--> statement-breakpoint
PRAGMA
foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_agent_profiles\`
(
    \`id\`          text PRIMARY KEY                  NOT NULL,
    \`project_id\`  text                              NOT NULL,
    \`agent\`       text                              NOT NULL,
    \`name\`        text                              NOT NULL,
    \`config_json\` text                              NOT NULL,
    \`created_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`  integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_agent_profiles\`("id", "project_id", "agent", "name", "config_json", "created_at", "updated_at")
SELECT "id", "project_id", "agent", "name", "config_json", "created_at", "updated_at"
FROM \`agent_profiles\`;--> statement-breakpoint
DROP TABLE \`agent_profiles\`;--> statement-breakpoint
ALTER TABLE \`__new_agent_profiles\` RENAME TO \`agent_profiles\`;--> statement-breakpoint
PRAGMA
foreign_keys=ON;--> statement-breakpoint
CREATE TABLE \`__new_attempt_logs\`
(
    \`id\`         text PRIMARY KEY                  NOT NULL,
    \`attempt_id\` text                              NOT NULL,
    \`ts\`         integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`level\`      text    DEFAULT 'info'            NOT NULL,
    \`message\`    text                              NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_attempt_logs\`("id", "attempt_id", "ts", "level", "message")
SELECT "id", "attempt_id", "ts", "level", "message"
FROM \`attempt_logs\`;--> statement-breakpoint
DROP TABLE \`attempt_logs\`;--> statement-breakpoint
ALTER TABLE \`__new_attempt_logs\` RENAME TO \`attempt_logs\`;--> statement-breakpoint
CREATE TABLE \`__new_attempts\`
(
    \`id\`            text PRIMARY KEY                  NOT NULL,
    \`card_id\`       text                              NOT NULL,
    \`board_id\`      text                              NOT NULL,
    \`agent\`         text                              NOT NULL,
    \`status\`        text                              NOT NULL,
    \`base_branch\`   text    DEFAULT 'main'            NOT NULL,
    \`branch_name\`   text                              NOT NULL,
    \`worktree_path\` text                              NOT NULL,
    \`session_id\`    text,
    \`started_at\`    integer,
    \`ended_at\`      integer,
    \`created_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`    integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_attempts\`("id", "card_id", "board_id", "agent", "status", "base_branch", "branch_name",
                             "worktree_path", "session_id", "started_at", "ended_at", "created_at", "updated_at")
SELECT "id",
       "card_id",
       "board_id",
       "agent",
       "status",
       "base_branch",
       "branch_name",
       "worktree_path",
       "session_id",
       "started_at",
       "ended_at",
       "created_at",
       "updated_at"
FROM \`attempts\`;--> statement-breakpoint
DROP TABLE \`attempts\`;--> statement-breakpoint
ALTER TABLE \`__new_attempts\` RENAME TO \`attempts\`;--> statement-breakpoint
CREATE TABLE \`__new_conversation_items\`
(
    \`id\`         text PRIMARY KEY                  NOT NULL,
    \`attempt_id\` text                              NOT NULL,
    \`seq\`        integer                           NOT NULL,
    \`ts\`         integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`item_json\`  text                              NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_conversation_items\`("id", "attempt_id", "seq", "ts", "item_json")
SELECT "id", "attempt_id", "seq", "ts", "item_json"
FROM \`conversation_items\`;--> statement-breakpoint
DROP TABLE \`conversation_items\`;--> statement-breakpoint
ALTER TABLE \`__new_conversation_items\` RENAME TO \`conversation_items\`;--> statement-breakpoint
CREATE TABLE \`__new_github_issues\`
(
    \`id\`             text PRIMARY KEY                  NOT NULL,
    \`board_id\`       text                              NOT NULL,
    \`card_id\`        text                              NOT NULL,
    \`owner\`          text                              NOT NULL,
    \`repo\`           text                              NOT NULL,
    \`issue_id\`       text                              NOT NULL,
    \`issue_number\`   integer                           NOT NULL,
    \`title_snapshot\` text                              NOT NULL,
    \`url\`            text                              NOT NULL,
    \`state\`          text                              NOT NULL,
    \`created_at\`     integer DEFAULT CURRENT_TIMESTAMP NOT NULL,
    \`updated_at\`     integer DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_github_issues\`("id", "board_id", "card_id", "owner", "repo", "issue_id", "issue_number",
                                  "title_snapshot", "url", "state", "created_at", "updated_at")
SELECT "id",
       "board_id",
       "card_id",
       "owner",
       "repo",
       "issue_id",
       "issue_number",
       "title_snapshot",
       "url",
       "state",
       "created_at",
       "updated_at"
FROM \`github_issues\`;--> statement-breakpoint
DROP TABLE \`github_issues\`;--> statement-breakpoint
ALTER TABLE \`__new_github_issues\` RENAME TO \`github_issues\`;` },
  { tag: "0002_little_invaders", sql: `ALTER TABLE \`app_settings\` DROP COLUMN \`git_signoff\`;--> statement-breakpoint
ALTER TABLE \`app_settings\` DROP COLUMN \`git_gpg_sign\`;--> statement-breakpoint
ALTER TABLE \`app_settings\` DROP COLUMN \`gh_default_pr_base\`;--> statement-breakpoint
ALTER TABLE \`app_settings\` DROP COLUMN \`gh_default_reviewers\`;--> statement-breakpoint
ALTER TABLE \`app_settings\` DROP COLUMN \`gh_default_assignees\`;` },
  { tag: "0003_tearful_chronomancer", sql: `PRAGMA
foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_app_settings\`
(
    \`id\`                   text PRIMARY KEY DEFAULT 'singleton'                   NOT NULL,
    \`theme\`                text             DEFAULT 'system'                      NOT NULL,
    \`language\`             text             DEFAULT 'browser'                     NOT NULL,
    \`telemetry_enabled\`    integer          DEFAULT false                         NOT NULL,
    \`notif_toast_sounds\`   integer          DEFAULT false                         NOT NULL,
    \`notif_desktop\`        integer          DEFAULT false                         NOT NULL,
    \`editor_type\`          text             DEFAULT 'VS_CODE'                     NOT NULL,
    \`editor_command\`       text,
    \`git_user_name\`        text,
    \`git_user_email\`       text,
    \`worktrees_root\`       text             DEFAULT '~/kanbanAI/worktrees'        NOT NULL,
    \`branch_template\`      text             DEFAULT '{prefix}/{ticketKey}-{slug}' NOT NULL,
    \`gh_pr_title_template\` text,
    \`gh_pr_body_template\`  text,
    \`gh_autolink_tickets\`  integer          DEFAULT true                          NOT NULL,
    \`created_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL,
    \`updated_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_app_settings\`("id", "theme", "language", "telemetry_enabled", "notif_toast_sounds", "notif_desktop",
                                 "editor_type", "editor_command", "git_user_name", "git_user_email", "worktrees_root",
                                 "branch_template", "gh_pr_title_template", "gh_pr_body_template",
                                 "gh_autolink_tickets", "created_at", "updated_at")
SELECT "id",
       "theme",
       "language",
       "telemetry_enabled",
       "notif_toast_sounds",
       "notif_desktop",
       "editor_type",
       "editor_command",
       "git_user_name",
       "git_user_email",
       "worktrees_root",
       "branch_template",
       "gh_pr_title_template",
       "gh_pr_body_template",
       "gh_autolink_tickets",
       "created_at",
       "updated_at"
FROM \`app_settings\`;--> statement-breakpoint
DROP TABLE \`app_settings\`;--> statement-breakpoint
ALTER TABLE \`__new_app_settings\` RENAME TO \`app_settings\`;--> statement-breakpoint
PRAGMA
foreign_keys=ON;` },
  { tag: "0004_soft_sentry", sql: `PRAGMA
foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE \`__new_app_settings\`
(
    \`id\`                   text PRIMARY KEY DEFAULT 'singleton'                   NOT NULL,
    \`theme\`                text             DEFAULT 'system'                      NOT NULL,
    \`language\`             text             DEFAULT 'browser'                     NOT NULL,
    \`telemetry_enabled\`    integer          DEFAULT false                         NOT NULL,
    \`notif_toast_sounds\`   integer          DEFAULT false                         NOT NULL,
    \`notif_desktop\`        integer          DEFAULT false                         NOT NULL,
    \`editor_type\`          text             DEFAULT 'VS_CODE'                     NOT NULL,
    \`editor_command\`       text,
    \`git_user_name\`        text,
    \`git_user_email\`       text,
    \`worktrees_root\`       text             DEFAULT '/tmp/kanbanai/worktrees'     NOT NULL,
    \`branch_template\`      text             DEFAULT '{prefix}/{ticketKey}-{slug}' NOT NULL,
    \`gh_pr_title_template\` text,
    \`gh_pr_body_template\`  text,
    \`gh_autolink_tickets\`  integer          DEFAULT true                          NOT NULL,
    \`created_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL,
    \`updated_at\`           integer          DEFAULT CURRENT_TIMESTAMP             NOT NULL
);
--> statement-breakpoint
INSERT INTO \`__new_app_settings\`("id", "theme", "language", "telemetry_enabled", "notif_toast_sounds", "notif_desktop",
                                 "editor_type", "editor_command", "git_user_name", "git_user_email", "worktrees_root",
                                 "branch_template", "gh_pr_title_template", "gh_pr_body_template",
                                 "gh_autolink_tickets", "created_at", "updated_at")
SELECT "id",
       "theme",
       "language",
       "telemetry_enabled",
       "notif_toast_sounds",
       "notif_desktop",
       "editor_type",
       "editor_command",
       "git_user_name",
       "git_user_email",
       "worktrees_root",
       "branch_template",
       "gh_pr_title_template",
       "gh_pr_body_template",
       "gh_autolink_tickets",
       "created_at",
       "updated_at"
FROM \`app_settings\`;--> statement-breakpoint
DROP TABLE \`app_settings\`;--> statement-breakpoint
ALTER TABLE \`__new_app_settings\` RENAME TO \`app_settings\`;--> statement-breakpoint
PRAGMA
foreign_keys=ON;` },
  { tag: "0005_retire_auto_cleanup", sql: `ALTER TABLE "project_settings" DROP COLUMN "auto_cleanup";
` },
  { tag: "0006_card_dependencies", sql: `CREATE TABLE IF NOT EXISTS \`card_dependencies\`
(
    \`card_id\`
    text
    NOT
    NULL,
    \`depends_on_card_id\`
    text
    NOT
    NULL,
    \`created_at\`
    integer
    DEFAULT
    CURRENT_TIMESTAMP
    NOT
    NULL,
    FOREIGN
    KEY
(
    \`card_id\`
) REFERENCES \`cards\`
(
    \`id\`
) ON UPDATE no action
  ON DELETE cascade,
    FOREIGN KEY
(
    \`depends_on_card_id\`
) REFERENCES \`cards\`
(
    \`id\`
)
  ON UPDATE no action
  ON DELETE cascade
    );
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS \`card_deps_unique\` ON \`card_dependencies\` (\`card_id\`, \`depends_on_card_id\`);

` },
] as const