import fs from "node:fs/promises";
import path from "node:path";

const root = new URL("..", import.meta.url);

const resolvePath = (relative: string) =>
  path.resolve(new URL(relative, root).pathname);

async function collectFiles(dir: string): Promise<string[]> {
  const out: string[] = [];
  const entries = await fs.readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await collectFiles(full)));
    } else if (entry.isFile()) {
      out.push(full);
    }
  }
  return out;
}

async function main() {
  const staticDir = resolvePath("server/static");

  const exists = await fs
    .access(staticDir)
    .then(() => true)
    .catch(() => false);
  if (!exists) {
    console.warn(
      "[build-static-bundle] server/static not found; generated bundle will be empty",
    );
  }

  const files = exists ? await collectFiles(staticDir) : [];

  const entries: { key: string; value: string }[] = [];

  for (const fullPath of files) {
    const rel = path
      .relative(staticDir, fullPath)
      .split(path.sep)
      .join("/");

    const httpPath =
      rel === "index.html" ? "/" : "/" + rel.replace(/^[/]+/, "");

    const contents = await fs.readFile(fullPath, "utf8");
    entries.push({ key: httpPath, value: contents });

    // Also support /index.html explicitly for the SPA shell.
    if (httpPath === "/") {
      entries.push({ key: "/index.html", value: contents });
    }
  }

  // Sort keys for deterministic output
  entries.sort((a, b) => a.key.localeCompare(b.key));

  const lines: string[] = [];
  lines.push(
    "// AUTO-GENERATED by scripts/build-static-bundle.ts; DO NOT EDIT BY HAND.",
  );
  lines.push("export const staticBundle = {");
  for (const { key, value } of entries) {
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(value)},`);
  }
  lines.push("};", "");

  const outPath = resolvePath("server/dist/src/static-bundle.generated.js");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");

  console.log(
    `[build-static-bundle] wrote static-bundle.generated.js with ${entries.length} entries`,
  );
}

main().catch((error) => {
  console.error("[build-static-bundle] failed", error);
  process.exit(1);
});
