import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

const root = new URL("..", import.meta.url);

const resolvePath = (relative: string) =>
  path.resolve(new URL(relative, root).pathname);

async function main() {
  const drizzleDir = resolvePath("server/drizzle");

  const exists = await fs
    .access(drizzleDir)
    .then(() => true)
    .catch(() => false);

  if (!exists) {
    console.error(
      "[build-drizzle-migration-bundle] server/drizzle not found; cannot build migration bundle",
    );
    process.exit(1);
  }

  const files = await fs.readdir(drizzleDir, { withFileTypes: true });
  const sqlFiles = files
    .filter(
      (e) => e.isFile() && e.name.toLowerCase().endsWith(".sql"),
    )
    .map((e) => e.name)
    .sort();

  const migrations: {
    id: string;
    name: string;
    checksum: string;
    sql: string;
  }[] = [];

  for (const file of sqlFiles) {
    const id = file.replace(/\.sql$/i, "");
    const sqlPath = path.join(drizzleDir, file);
    const sql = await fs.readFile(sqlPath, "utf8");
    const checksum = crypto.createHash("sha256").update(sql).digest("hex");
    migrations.push({
      id,
      name: id,
      checksum,
      sql,
    });
  }

  if (migrations.length === 0) {
    console.error(
      "[build-drizzle-migration-bundle] no Drizzle migrations found in server/drizzle; refusing to generate empty bundle",
    );
    process.exit(1);
  }

  const lines: string[] = [];
  lines.push(
    "// AUTO-GENERATED by scripts/build-drizzle-migration-bundle.ts; DO NOT EDIT BY HAND.",
  );
  lines.push(
    "export type DrizzleMigrationSpec = { id: string; name: string; checksum: string; sql: string };",
  );
  lines.push("export const drizzleMigrations: DrizzleMigrationSpec[] = [");
  for (const m of migrations) {
    lines.push(
      `  { id: ${JSON.stringify(m.id)}, name: ${JSON.stringify(
        m.name,
      )}, checksum: ${JSON.stringify(m.checksum)}, sql: ${JSON.stringify(
        m.sql,
      )} },`,
    );
  }
  lines.push("];", "");

  const outPath = resolvePath("server/drizzle/migration-data.generated.ts");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");

  console.log(
    `[build-drizzle-migration-bundle] wrote migration-data.generated.ts with ${migrations.length} migrations`,
  );
}

main().catch((error) => {
  console.error("[build-drizzle-migration-bundle] failed", error);
  process.exit(1);
});
