import fs from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";

const root = new URL("..", import.meta.url);

const resolvePath = (relative: string) =>
  path.resolve(new URL(relative, root).pathname);

async function main() {
  const prismaDir = resolvePath("server/prisma");
  const migrationsRoot = path.join(prismaDir, "migrations");

  const exists = await fs
    .access(migrationsRoot)
    .then(() => true)
    .catch(() => false);

  if (!exists) {
    console.warn(
      "[build-prisma-migration-bundle] prisma/migrations not found; generated bundle will be empty",
    );
  }

  const migrations: {
    id: string;
    name: string;
    checksum: string;
    sql: string;
  }[] = [];

  if (exists) {
    const entries = await fs.readdir(migrationsRoot, { withFileTypes: true });
    const dirs = entries
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
      .sort();

    for (const dir of dirs) {
      const migrationSqlPath = path.join(migrationsRoot, dir, "migration.sql");
      const sql = await fs.readFile(migrationSqlPath, "utf8");
      const checksum = crypto.createHash("sha256").update(sql).digest("hex");
      migrations.push({
        id: dir,
        name: dir,
        checksum,
        sql,
      });
    }
  }

  const lines: string[] = [];
  lines.push(
    "// AUTO-GENERATED by scripts/build-prisma-migration-bundle.ts; DO NOT EDIT BY HAND.",
  );
  lines.push(
    "export type PrismaMigrationSpec = { id: string; name: string; checksum: string; sql: string };",
  );
  lines.push("export const prismaMigrations: PrismaMigrationSpec[] = [");
  for (const m of migrations) {
    lines.push(
      `  { id: ${JSON.stringify(m.id)}, name: ${JSON.stringify(m.name)}, checksum: ${JSON.stringify(m.checksum)}, sql: ${JSON.stringify(m.sql)} },`,
    );
  }
  lines.push("];", "");

  const outPath = resolvePath("server/prisma/migration-data.generated.ts");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");

  console.log(
    `[build-prisma-migration-bundle] wrote migration-data.generated.ts with ${migrations.length} migrations`,
  );
}

main().catch((error) => {
  console.error("[build-prisma-migration-bundle] failed", error);
  process.exit(1);
});
