import fs from "node:fs/promises";
import path from "node:path";

const root = new URL("..", import.meta.url);

const resolvePath = (relative: string) =>
  path.resolve(new URL(relative, root).pathname);

async function main() {
  const drizzleDir = resolvePath("server/drizzle");
  const journalPath = path.join(drizzleDir, "meta", "_journal.json");

  const journal = await fs.readFile(journalPath, "utf8");

  const entries = await fs.readdir(drizzleDir, { withFileTypes: true });
  const sqlFiles = entries
    .filter((e) => e.isFile() && e.name.endsWith(".sql"))
    .map((e) => e.name)
    .sort();

  const lines: string[] = [];
  lines.push(
    "// AUTO-GENERATED by scripts/build-migration-data.ts; DO NOT EDIT BY HAND.",
  );
  lines.push(
    "export const migrationData: Record<string, string> = {",
  );
  lines.push(
    `  "meta/_journal.json": ${JSON.stringify(journal)},`,
  );

  for (const filename of sqlFiles) {
    const fullPath = path.join(drizzleDir, filename);
    const sql = await fs.readFile(fullPath, "utf8");
    lines.push(
      `  ${JSON.stringify(filename)}: ${JSON.stringify(sql)},`,
    );
  }

  lines.push("};", "");

  const outPath = path.join(drizzleDir, "migration-data.generated.ts");
  await fs.writeFile(outPath, lines.join("\n"), "utf8");

  console.log(
    `[build-migration-data] wrote migration-data.generated.ts with ${sqlFiles.length} migrations`,
  );
}

main().catch((error) => {
  console.error("[build-migration-data] failed", error);
  process.exit(1);
});

