import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dir, '..')
const drizzleDir = path.join(root, 'server', 'drizzle')
const journalPath = path.join(drizzleDir, 'meta', '_journal.json')
const outputPath = path.join(drizzleDir, 'migration-data.generated.ts')

async function readFileSafe(file: string) {
  const handle = Bun.file(file)
  if (!(await handle.exists())) {
    throw new Error(`[bundle-migrations] missing file: ${file}`)
  }
  return handle.text()
}

async function collectMigrations() {
  const map: Record<string, string> = {}

  // journal
  map['meta/_journal.json'] = await readFileSafe(journalPath)

  const entries = await fs.promises.readdir(drizzleDir, { withFileTypes: true })
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.sql')) continue
    const abs = path.join(drizzleDir, entry.name)
    map[entry.name] = await readFileSafe(abs)
  }

  return map
}

function toTs(map: Record<string, string>) {
  const serialized = JSON.stringify(map, null, 2)
  return `// Auto-generated by scripts/bundle-drizzle-migrations.ts. Do not edit manually.\nexport const migrationData: Record<string, string> = ${serialized} as const;\n`
}

async function main() {
  const migrations = await collectMigrations()
  const ts = toTs(migrations)
  await fs.promises.writeFile(outputPath, ts, 'utf8')
  console.log(`[bundle-migrations] wrote ${outputPath}`)
}

main().catch((error) => {
  console.error('[bundle-migrations] failed', error)
  process.exit(1)
})
