/**
 * Generate server/src/drizzle-embed.ts from server/drizzle folder.
 * Embeds meta/_journal.json and all .sql files as strings.
 */
import {promises as fs} from 'fs'
import path from 'path'

const DRIZZLE_DIR = path.resolve(process.cwd(), 'server', 'drizzle')
const OUTPUT = path.resolve(process.cwd(), 'server', 'src', 'drizzle-embed.ts')

async function main() {
    const metaPath = path.join(DRIZZLE_DIR, 'meta', '_journal.json')
    const metaRaw = await fs.readFile(metaPath, 'utf8')
    const meta = JSON.parse(metaRaw) as {
        version: string;
        dialect: string;
        entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[]
    }
    const entries = meta.entries

    const lines: string[] = []
    lines.push('// AUTO-GENERATED by scripts/embed-drizzle.ts. DO NOT EDIT.')
    lines.push('export type EmbeddedMeta = { version: string; dialect: string; entries: { idx: number; version: string; when: number; tag: string; breakpoints: boolean }[] }')
    lines.push('export const EMBEDDED_META: EmbeddedMeta = ' + JSON.stringify(meta, null, 2))
    lines.push('')
    lines.push('export type EmbeddedMigration = { tag: string; sql: string }')
    lines.push('export const EMBEDDED_MIGRATIONS: EmbeddedMigration[] = [')
    for (const e of entries) {
        const sql = await fs.readFile(path.join(DRIZZLE_DIR, `${e.tag}.sql`), 'utf8')
        const esc = sql.replace(/`/g, '\\`')
        lines.push(`  { tag: ${JSON.stringify(e.tag)}, sql: \`${esc}\` },`)
    }
    lines.push('] as const')
    await fs.writeFile(OUTPUT, lines.join('\n'))
    console.log(`[embed-drizzle] Wrote ${entries.length} migrations to ${path.relative(process.cwd(), OUTPUT)}`)
}

// eslint-disable-next-line unicorn/prefer-top-level-await
main().catch((err) => {
    console.error('[embed-drizzle] failed:', err)
    process.exit(1)
})
