export const DEFAULT_GITHUB_REPO = 'activadee/kanban-ai'

export const KANBANAI_HOME_ENV = 'KANBANAI_HOME'
export const KANBANAI_BINARY_VERSION_ENV = 'KANBANAI_BINARY_VERSION'
export const KANBANAI_GITHUB_REPO_ENV = 'KANBANAI_GITHUB_REPO'
export const KANBANAI_NO_UPDATE_CHECK_ENV = 'KANBANAI_NO_UPDATE_CHECK'
export const KANBANAI_ASSUME_YES_ENV = 'KANBANAI_ASSUME_YES'
export const KANBANAI_ASSUME_NO_ENV = 'KANBANAI_ASSUME_NO'

export const CACHE_DIR_NAME = '.kanbanAI'
export const CACHE_SUBDIR_BINARY = 'binary'
